### ISSUE TITLE
ISSUE WITH IMPLEMENTING THE AES C CODE IN STM32F407

### ISSUE THREAD

**Issue by DHONI123456** [m3y54m/aes-in-c#1]
I AM TRYING TO HAVE AES ENCRYPTION FOR MY DATA (120 bytes in one second) WHICH IS TRANSMITTED THROUGH UART PERIPHERAL OF MY MICRO-CONTROLLER STM32F407 WHICH RUNS AT 168MHZ. SINCE THE MICRO-CONTROLLER DOESN'T HAVE A CRYPTO LIBRARY, I TRIED TO RUN THIS CODE AND I WANTED TO KNOW THE TIME IT TAKES FOR ENCRYPTION . IN THE CODE, IT  SENT 16 BYTES OF DATA. SO IF I CAN FIND THE TIME FOR 16 BYTES, I COULD EASILY CALCULATE THE TIME FOR  ENCRYPTION OF 120 BYTES BEFORE UART TRANSMISSION. TO CALCULATE THE TIME TAKEN, I JUST SET LED PIN HIGH  BEFORE ENCRYPTION AND AFTER THE ENCRYPTION FUNCTION(AFTER CYPHER-TEXT IS GENERATED) I TURNED THE PIN LOW. THEN I TRIED TO CALCULATE THE TIMING. I ACTUALLY PUT A DELAY OF 1 SECOND ALSO. BUT AS SOON AS THE CODE RUNNING STARTS, THE EXECUTION MOVES TO THE HARD FAULT  AND PROGRAM EXECUTION STOPS. HOW TO RESOLVE THE ISSUE. ALSO PLEASE HELP ME BY TELLING WHETHER I AM DOING SOMETHING IN A WRONG WAY TO CALCULATE THE TIMING OF AES FOR 120 BYTE DATA? LOOKING FORWARD FOR YOUR REPLY.
THANKS & REGARDS

![Capture](https://github.com/m3y54m/aes-in-c/assets/136151179/8024abd2-b2cb-4add-a480-b24939f85041)

**Comment by m3y54m** [comment]
**As stated on the first page of the repository, this code is very BASIC and only for EDUCATIONAL PURPOSES. I strongly recommend that you do not use it in your projects, especially in embedded projects that have very limited resources.

This code is not optimal in using memory resources, and even it does have some security issues. SO DO NOT USE IT FOR REAL PROJECTS!**

With all the above in mind I assume that you are running this code on the STM32F407 for evaluation or learning purposes only. 

I wrote this code when I didn't know much about C language and my code may have memory leak problems. Every malloc() should have a corresponding free() somewhere in the code, but this is not the case in my code. I guess the HARD_FAULT error occurred because of this. I will fix my code as soon as I can.

Another point is that I don't see anything in your code to measure the time! You only put two delays that have nothing to do with time measurement. You should use one of micro-controller timers to measure time.

**Comment by m3y54m** [comment]
I made some changes in the code in commit fca0091. Please inform me if it solved your problem.
